version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: tech_challenge_3_postgres
    environment:
      POSTGRES_DB: gestao_hospitalar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata_tc3:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gestao_hospitalar"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  pgdata_tc3: {}
