version: '3.9'


services:
  postgres:
    image: postgres:16
    container_name: tech_challenge_3_postgres
    environment:
      POSTGRES_DB: gestao_hospitalar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata_tc3:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gestao_hospitalar"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 1234
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

volumes:
  pgdata_tc3: {}
  rabbitmq_data: {}
