server:
  port: 8085

spring:
  application:
    name: historicoConsulta
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 1234
  graphql:
    path: /graphql
    graphiql:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: historico_db
      username: root
      password: root
      authentication-database: admin
