server:
  port: 9090

spring:
  application:
    name: service-notificacoes
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 1234

  task:
    scheduling:
      enabled: false

logging:
  level:
    org.springframework.amqp: DEBUG